global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using OneLetterShor;
global using OneLetterShor.HideAndSeek;
global using UnityEngine;
global using static OneLetterShor.HideAndSeek.Tests.Assertions;
global using Logger = OneLetterShor.HideAndSeek.Logging.Logger;